Vagrant.configure("2") do |config|
  config.vm.define :workhorse do |workhorse|
    workhorse.vm.hostname = "visoft-workhorse"
    workhorse.vm.box = "fedora/39-cloud-base"
    workhorse.vm.box_version = "39.20231031.1"

    workhorse.vm.provider :libvirt do |libvirt|
      libvirt.storage_pool_name = "fast"
      libvirt.management_network_mode = "none"
      libvirt.driver = "kvm"
      libvirt.uri = "qemu:///system"
      libvirt.memory = 98304
      libvirt.cpu_mode = "host-passthrough"
      libvirt.cpus = 60
      libvirt.cputopology sockets: "1", cores: "30", threads: "2"
    end

    workhorse.vm.network "public_network", dev: "bridge0", mode: "bridge", type: "bridge", mac: "52:54:00:19:63:3D"

    workhorse.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end
end
